//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace employee_crud_operations
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        
        public int id { get; set; }

        [Required(ErrorMessage ="Enter The Name")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Enter The Description")]
        public string Description { get; set; }
    }
}
